
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws.exemple.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://ws.exemple.org/", className = "proxy.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://ws.exemple.org/", className = "proxy.GetComptesResponse")
    @Action(input = "http://ws.exemple.org/BanqueService/getComptesRequest", output = "http://ws.exemple.org/BanqueService/getComptesResponse")
    public Compte getComptes(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listcomptes", targetNamespace = "http://ws.exemple.org/", className = "proxy.Listcomptes")
    @ResponseWrapper(localName = "listcomptesResponse", targetNamespace = "http://ws.exemple.org/", className = "proxy.ListcomptesResponse")
    @Action(input = "http://ws.exemple.org/BanqueService/listcomptesRequest", output = "http://ws.exemple.org/BanqueService/listcomptesResponse")
    public List<Compte> listcomptes();

}
